Lesson01
TaranyukK/TestGuru pull request #1
Opened 2024-04-26 18:40 UTC by TaranyukK

2024-04-27 07:54 UTC, VidgarVii requested changes

2024-04-27 07:54 UTC, VidgarVii commented on README.md
> +* Tests
как-то мало получилось сущностей )))

список сущностей приложения обычно выводится из сценария использования приложения

сценарий использования приложения примерно такой:
- Пользователь заходит на сайт
- он выбирает Тест
- Тест может принадлежать к одной из Категорий
- Тест состоит из Вопросов
- на каждый Вопрос есть несколько Ответов
- Пользователь выбирает один или несколько Ответов, чтобы ответить на каждый из Вопросов
- Результат тестирования сохраняется

2024-04-27 07:54 UTC, VidgarVii commented on app/controllers/pages_controller.rb
> +class PagesController < ApplicationController
`html` файлы целиком статические
их будет оптимальнее отдать вообще в обход рельсового приложения (так будет работать быстрее, да и рельсам с этими файлами делать то нечего)
для этого их достаточно поместить в директорию `public`

роуты при этом не нужны и контроллеры тоже
(путь к файлу внутри директории `public` должен соответствовать пути, по которому этот файл должен быть доступен)

2024-04-27 07:54 UTC, VidgarVii commented on app/views/pages/author.html.erb
> +<a href='https://github.com/TaranyukK'>github</a>
в конце файла надо отставлять 1 пустую строчку. Это указатель на конец файла. Сейчас система думает, что происходит обрыв файла. Даже гитхаб ругается. No new lina at end of file. Многие компиляторы тут выдадут ошибку. Руби частично компилируемый язык. И такой разрыв легко проглотит. Но в реальных проектах это как красная тряпка для быка. Так что тренируем дисциплину и больше такого не совершаем! В руби за чистоту кода!

2024-04-27 07:54 UTC, VidgarVii commented on app/views/pages/author.html.erb
> +<a href='https://github.com/TaranyukK'>github</a>
ссылки на сторонние ресурсы правильно открывать в новой вкладке и хорошо бы добавить опцию rel=nofollow rel=noopener. Так клиента сохраним и поискового робота дальше не пустим

2024-04-27 07:54 UTC, VidgarVii commented on config/application.rb
> +    config.i18n.default_locale = :en
для обучения предлагаю поставить локаль ru. Тем более у тебя на страницах текст на русском.

2024-04-27 07:54 UTC, VidgarVii commented on config/initializers/version.rb
> +VERSION = [MAJOR, MINOR, PATCH].join('.')
не стоит засорять глобальное пространство
версия относится к приложению, так что и константу нужно объявить в его контексте

посмотри к примеру в файл `config/application.rb` в какой модуль обернуто все твое приложение (9-я строка)

```ruby
module TestGuru
  class Application < Rails::Application
    VERSION = '0.1.0'.freeze
  end
end
```

2024-04-27 07:54 UTC, VidgarVii commented on config/initializers/version.rb
> +PATCH = 0
для определения 1 строки выделять 3 константы лишнее

2024-04-27 13:23 UTC, VidgarVii requested changes

2024-04-27 13:23 UTC, VidgarVii commented on config/application.rb
> +    VERSION = '0.1.0'.freeze
определять версию приложения как раз надо в config/initializers/version.rb

2024-04-27 13:23 UTC, VidgarVii commented on config/initializers/version.rb
> +VERSION = [MAJOR, MINOR, PATCH].join('.')
тут ни чего не исправлено

2024-04-27 13:23 UTC, VidgarVii commented on public/about.html
> +<h1>TestGuru</h1>
файлы из `public` отдаются минуя контроллеры "как есть", т.е. без лэйаута
это означает, что здесь должен быть полноценная `html` страница, которая открывается тегом `<!DOCTYPE html>` и содержит теги `<html>`, `<head>`, `<body>` и т.д.

2024-04-27 13:23 UTC, VidgarVii commented on public/about.html
> +<h4>Разработано с помощью уроков от онлайн-школы <a href='https://thinknetica.com/'>Thinknetica</a></h4>
не исправлено https://github.com/TaranyukK/TestGuru/pull/1#discussion_r1581753464

2024-04-27 13:23 UTC, VidgarVii commented on test/controllers/about_controller_test.rb
> +require "test_helper"
этот тест не нужен

2024-04-28 18:16 UTC, BubuntuClu requested changes

2024-04-28 18:16 UTC, BubuntuClu commented on config/initializers/version.rb
> +VERSION = '0.1.0'.freeze
это все еще не исправлено.
ты создал "глобальную" константу. она не принадлежит никакому модулю/классу и тд. это плохо. напиши в этом файле такой код, чтобы можно было из консоли получить версию приложения написал команду `TestGuru.current_version`

2024-04-28 18:16 UTC, BubuntuClu commented on config/application.rb
> +    config.i18n.default_locale = :ru
поставь пока английский язык, чтобы ошибки были понятные. потом при добавлении русской локализации можно будет переключиться без последствий

2024-04-28 18:16 UTC, BubuntuClu commented on public/about.html
> +</html>
видишь тут красный знак нарисован у последней строки? это ругается гитхаб, что нет пустой строки в конце файла. в IDE сделай настройку, чтобы добавлялась пустая строка в конец файла. Это исправит ворнинг на гитхабе

2024-05-02 06:40 UTC, VidgarVii commented on README.md
> +* Results
не хватает Ответов

2024-05-02 19:58 UTC, merged