Lesson05
TaranyukK/TestGuru pull request #5
Opened 2024-05-17 12:29 UTC by TaranyukK

2024-05-17 12:30 UTC, TaranyukK commented on app/models/question.rb
> +  validates :answers, length: { in: 1..4 }
Не совсем уверен на счет этой валидации. Делал проверку, все работает.

2024-05-17 16:36 UTC, VidgarVii requested changes

2024-05-17 16:36 UTC, VidgarVii commented on app/models/answer.rb
> +  scope :correct, -> { where(correct: true) }
скоупы по сути являются методами класса и их рекомендуют писать после ассоциаций и валидаций

2024-05-17 16:36 UTC, VidgarVii commented on app/models/category.rb
> +  default_scope { order(title: :asc) }
`default_scope` глобально меняет поведение всех запросов к модели
поэтому его [рекомендуют](https://github.com/rubocop-hq/rails-style-guide#macro-style-methods) записывать в самом верху класса

2024-05-17 16:36 UTC, VidgarVii commented on app/models/question.rb
> +  validates :answers, length: { in: 1..4 }
всегда надо тестировать код) Эта валидация даже не запустится при создании Ответа. Потому что она написана в модели Вопрос. И даже если просто перенести код, все-ровно не будет работать. Тестируй код в консоли

2024-05-17 16:36 UTC, VidgarVii commented on app/models/user.rb
> +  scope :tests_by_level, -> (level) { where(level: level) }
принципиально неверно пытаться реализовывать инстанс метод через скоуп
скоуп по сути - это класс-метод и заменять инстанс метод класс-методом по крайней мере странно

2024-05-18 12:36 UTC, VidgarVii requested changes

2024-05-18 12:36 UTC, VidgarVii commented on app/models/answer.rb
> +    errors.add(:number_of_answers, 'should be between 1 and 4') if question.answers.count > 4
тут ошибка инваринтности.
Позволит создать 5 ответов

2024-05-18 22:05 UTC, TaranyukK commented on app/models/answer.rb
> +    errors.add(:number_of_answers, 'should be between 1 and 4') if question.answers.count > 4
Обновил код, прошу проверить

2024-05-20 22:01 UTC, merged