Lesson06
TaranyukK/TestGuru pull request #6
Opened 2024-05-21 11:14 UTC by TaranyukK

2024-05-21 11:16 UTC, TaranyukK commented on app/controllers/questions_controller.rb
> +  def destroy
Знаю, что не работает. Не совсем понял как реализовывать в рамках задания, поэтому вставил plain text

2024-05-21 16:44 UTC, VidgarVii requested changes

2024-05-21 16:44 UTC, VidgarVii commented on config/routes.rb
> +    resources :questions
для "облегчения" роутинга рекомендуется использовать (где это возможно и приемлемо) опцию `shallow: true`
Это уменьшит кол-во запросов в контроллере. Упростит код и укоротит http запрос
[вот](http://rusrails.ru/rails-routing#melkoe-vlozhenie) документация

2024-05-21 16:44 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +  def destroy
Просто надо взять объект вопроса и вызвать у него метод destroy

2024-05-21 16:44 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    render plain: result.join("\n")
Тут ведь ни чего не создаётся.

2024-05-22 04:40 UTC, VidgarVii requested changes

2024-05-22 04:40 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    @question = @test.questions.create(question_params)
При создании и обновлении ресурса нужно проверять валидацию, которая была прописана в модели. И если валидация не прошла, то рендерят форму и выводит ошибки(ошибки будем показывать далее по уроку)
По этому тут надо добавить проверку, записался ли объект в базу?
стандартный подход экшена create такой
```
@question = @test.questions.build(question_params)
if @question.save
  redirect_to @question
else
  render :new
end

2024-05-22 08:35 UTC, merged